09-Symfony/dialoguefiles/src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentaireRepository::class)]
class Commentaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $pseudo = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $message = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $date_enregistrement = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): static
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): static
    {
        $this->message = $message;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeImmutable
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeImmutable $date_enregistrement): static
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }
}

09-Symfony/dialoguefiles/src/Form/CommentaireType.php
<?php

namespace App\Form;

use App\Entity\Commentaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('pseudo')
            ->add('message')
            ->add('enregistrer', SubmitType::class, 
            [
                "label" => "Enregistrer"
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commentaire::class,
        ]);
    }
}

09-Symfony/dialoguefiles/src/Controller/CommentaireController.php
<?php

namespace App\Controller;

use App\Entity\Commentaire;
use App\Form\CommentaireType;
use App\Repository\CommentaireRepository;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class CommentaireController extends AbstractController
{
    #[Route('/commentaire', name: 'app_commentaire')]
    public function index(Request $request, EntityManagerInterface $em, CommentaireRepository $commentaireRepository): Response
    {

        $commentaire = new Commentaire;

        $formCommentaire = $this->createForm(CommentaireType::class, $commentaire);

        $formCommentaire->handleRequest($request);

        if ($formCommentaire->isSubmitted() && $formCommentaire->isValid()){

            $commentaire->setDateEnregistrement(new DateTimeImmutable());

            // dd($commentaire);

            $em->persist($commentaire);
            $em->flush();
        }


        // La méthode de requête findAll ne nous permet pas d'appliquer un orderby pour afficher les messages dans l'ordre du plus récent au plus ancien (desc), on peut éventuellement faire un array_reverse sur le résultat de la méthode findAll, sinon on peut utiliser findBy pour appliquer un orderBy
        // $commentaires = $commentaireRepository->findAll();
        // $commentaires = array_reverse($commentaires);
        $commentaires = $commentaireRepository->findBy([], ["date_enregistrement" => "desc"]);



        return $this->render('commentaire/index.html.twig', [
            "formCommentaire" => $formCommentaire,
            "commentaires" => $commentaires
        ]);
    }
}

09-Symfony/dialoguefiles/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Espace de dialogue{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        {% block stylesheets %}
        {% endblock %}

        {% block javascripts %}
            {% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
    <style>
        * {
            font-family: 'Roboto', sans-serif;
        }
        h1, h2, h3, h4, h5, h6 {
            font-family: 'Playfair Display', serif;
        }
    </style>
    </head>
    <body class="bg-secondary">
        {% block body %}{% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

09-Symfony/dialoguefiles/templates/commentaire/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Espace de dialogue
{% endblock %}

{% block body %}

	<div class="container bg-light">

		<div class="row">
			<div class="col-12">
				<h2 class="text-center p-5 border-bottom">Espace de dialogue</h2>
			</div>
			{{form(formCommentaire)}}
			</div>

			<div class="row">
				<div
					class="col-12">
					{# {{ dump(commentaires)}} #}
                    <p>Il y a  : <b>{{commentaires|length}}</b> messages </p>
					{% for commentaire in commentaires %}

						<div class="card w-75 mx-auto mb-3">
							<div class="card-header bg-dark text-white">
								Par {{commentaire.pseudo}}, le : {{commentaire.dateEnregistrement|date("d/m/Y à H:i:s", "Europe/Paris")}}
							</div>
							<div class="card-body">							
								<p class="card-text">{{commentaire.message}}</p>
							</div>
						</div>

					{% endfor %}
				</div>
			</div>

		</div>

	{% endblock %}